services:
  - type: web
    name: pawid
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: GROQ_API_KEY
        sync: false